### PR TITLE
Contract and Int64 in C kernel

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@lcw can you push which syncthreads is unecessary?

**Comment by lcw** [comment]
I think they are all necessary.  I can move one further down in the loop which I think might avoid the load chains.

**Comment by lcw** [comment]
Do you want me to do that?

**Comment by vchuravy** [comment]
That would be good.

**Comment by lcw** [comment]
Not sure if the push totally avoids the chains but there is more work between the barrier calls.

**Pull request merged**
