### PR TITLE
volumerhs performance

### PR DESCRIPTION
**Pull request by mwarusz**
The magic environmental variable for Julia version >= 1.4 is

JULIA_LLVM_ARGS="-instcombine-code-sinking=false"

The number of registers is still a bit higher than CUDA but the performance should be on par.

### CODE REVIEW

**Comment by vchuravy** [comment]
Oh fascinating! That is a very exciting discovery. Thank you.

**Comment by lcw** [comment]
This is awesome!  Below are the performance results I see.  With or without the environment variable CUDAnative seem to be faster than clang. 

Here is without the environment variable

```
❯ nvprof --print-gpu-trace julia --project=. volumerhs.jl
==19483== NVPROF is profiling process 19483, command: julia --project=. volumerhs.jl
┌ Warning: LLVM pre-9.0 detected, disabling debug info emission for CUDA kernels
└ @ CUDAnative ~/.julia/packages/CUDAnative/KZZcE/src/CUDAnative.jl:88
┌ Warning: You are using CUDNN 7.6.2 for CUDA 10.1.0 with CUDA toolkit 9.0.176; these might be incompatible.
└ @ CuArrays ~/.julia/packages/CuArrays/wYQnB/src/CuArrays.jl:122
┌ Warning: Calling CUDAdrv.@profile only informs an external profiler to start.
│ The user is responsible for launching Julia under a CUDA profiler like `nvprof`.
│
│ For improved usability, launch Julia under the Nsight Systems profiler:
│ $ nsys launch -t cuda,cublas,cudnn,nvtx julia
└ @ CUDAdrv.Profile ~/.julia/packages/CUDAdrv/mCr0O/src/profile.jl:42
==19483== Profiling application: julia --project=. volumerhs.jl
==19483== Profiling result:
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream  Name
22.5182s  12.366ms                    -               -         -         -         -  95.367MB  7.5315GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
31.4864s  2.0480us                    -               -         -         -         -        8B  3.7253MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
31.5941s  828.51us          (97657 1 1)       (256 1 1)        42        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_1 [35]
31.8456s  1.4720us                    -               -         -         -         -        8B  5.1830MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
31.9032s  115.65us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [54]
32.3208s  1.4720us                    -               -         -         -         -        8B  5.1830MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
32.4096s  131.65us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_3 [70]
32.6521s  34.835ms                    -               -         -         -         -  267.03MB  7.4860GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
32.6872s  117.02us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [79]
32.6873s  131.90us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_3 [81]
32.6875s  115.33us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [86]
33.0027s  1.8550us                    -               -         -         -         -        8B  4.1129MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
33.0630s  140.38us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_4 [102]
33.0634s  1.8560us                    -               -         -         -         -      100B  51.383MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
33.2336s  12.692ms                    -               -         -         -         -  95.367MB  7.3379GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
35.2215s  722.49us          (40000 1 1)         (5 5 1)       160  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__5 [121]
36.1001s  708.70us          (40000 1 1)         (5 5 1)       160  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__5 [124]

Regs: Number of registers used per CUDA thread. This number includes registers used internally by the CUDA driver and/or tools and can be more than what the compiler shows.
SSMem: Static shared memory allocated per CUDA block.
DSMem: Dynamic shared memory allocated per CUDA block.
SrcMemType: The type of source memory accessed by memory operation/copy
DstMemType: The type of destination memory accessed by memory operation/copy
```

and with the environment variable

```
❯ env JULIA_LLVM_ARGS="-instcombine-code-sinking=false" nvprof --print-gpu-trace julia --project=. volumerhs.jl
==19539== NVPROF is profiling process 19539, command: julia --project=. volumerhs.jl
┌ Warning: LLVM pre-9.0 detected, disabling debug info emission for CUDA kernels
└ @ CUDAnative ~/.julia/packages/CUDAnative/KZZcE/src/CUDAnative.jl:88
┌ Warning: You are using CUDNN 7.6.2 for CUDA 10.1.0 with CUDA toolkit 9.0.176; these might be incompatible.
└ @ CuArrays ~/.julia/packages/CuArrays/wYQnB/src/CuArrays.jl:122
┌ Warning: Calling CUDAdrv.@profile only informs an external profiler to start.
│ The user is responsible for launching Julia under a CUDA profiler like `nvprof`.
│
│ For improved usability, launch Julia under the Nsight Systems profiler:
│ $ nsys launch -t cuda,cublas,cudnn,nvtx julia
└ @ CUDAdrv.Profile ~/.julia/packages/CUDAdrv/mCr0O/src/profile.jl:42
==19539== Profiling application: julia --project=. volumerhs.jl
==19539== Profiling result:
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream  Name
21.7643s  12.128ms                    -               -         -         -         -  95.367MB  7.6792GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
30.4757s  1.9200us                    -               -         -         -         -        8B  3.9736MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
30.5797s  827.93us          (97657 1 1)       (256 1 1)        42        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_1 [35]
30.8261s  1.4720us                    -               -         -         -         -        8B  5.1830MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
30.8856s  115.78us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [54]
31.2942s  1.5040us                    -               -         -         -         -        8B  5.0727MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
31.3803s  131.62us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_3 [70]
31.6181s  33.987ms                    -               -         -         -         -  267.03MB  7.6728GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
31.6524s  117.09us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [79]
31.6525s  131.58us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_3 [81]
31.6526s  115.55us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_2 [86]
31.9578s  1.8560us                    -               -         -         -         -        8B  4.1107MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
32.0156s  140.51us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_4 [102]
32.0158s  1.8880us                    -               -         -         -         -      100B  50.512MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
32.1822s  12.224ms                    -               -         -         -         -  95.367MB  7.6189GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
34.1206s  736.09us          (40000 1 1)         (5 5 1)       109  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__5 [121]
34.9639s  721.75us          (40000 1 1)         (5 5 1)       109  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__5 [124]

Regs: Number of registers used per CUDA thread. This number includes registers used internally by the CUDA driver and/or tools and can be more than what the compiler shows.
SSMem: Static shared memory allocated per CUDA block.
DSMem: Dynamic shared memory allocated per CUDA block.
SrcMemType: The type of source memory accessed by memory operation/copy
DstMemType: The type of destination memory accessed by memory operation/copy
```

And for reference the clang version

```
❯ nvprof --print-gpu-trace ./volumerhs
==19645== NVPROF is profiling process 19645, command: ./volumerhs
==19645== Profiling application: ./volumerhs
==19645== Profiling result:
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream  Name
552.30ms  12.563ms                    -               -         -         -         -  95.367MB  7.4133GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
572.33ms  11.934ms                    -               -         -         -         -  95.367MB  7.8038GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
1.32062s  33.649ms                    -               -         -         -         -  267.03MB  7.7497GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
1.36991s  33.718ms                    -               -         -         -         -  267.03MB  7.7339GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
1.40381s  1.8880us                    -               -         -         -         -      100B  50.512MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
1.66608s  11.948ms                    -               -         -         -         -  95.367MB  7.7945GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
1.67803s  786.02us          (40000 1 1)         (5 5 1)        78  1.0742KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  void volumerhs<long=5, long=125, long=5>(float*, float const *, float const *, float, float const *, long) [119]

Regs: Number of registers used per CUDA thread. This number includes registers used internally by the CUDA driver and/or tools and can be more than what the compiler shows.
SSMem: Static shared memory allocated per CUDA block.
DSMem: Dynamic shared memory allocated per CUDA block.
SrcMemType: The type of source memory accessed by memory operation/copy
DstMemType: The type of destination memory accessed by memory operation/copy
```

**Comment by lcw** [comment]
We see the performance improvements in older versions of julia as well.

```
❯ nvprof --print-gpu-trace /opt/julia/1.2.0/bin/julia --project=. volumerhs.jl
==21447== NVPROF is profiling process 21447, command: /opt/julia/1.2.0/bin/julia --project=. volumerhs.jl
==21489== Warning: Child processes are not profiled. Use option --profile-child-processes to profile them.

┌ Warning: You are using CUDNN 7.6.2 for CUDA 10.1.0 with CUDA toolkit 9.0.176; these might be incompatible.
└ @ CuArrays ~/.julia/packages/CuArrays/wYQnB/src/CuArrays.jl:122
[ Info: Building the CUDAnative run-time library for your sm_70 device, this might take a while...
┌ Warning: Calling CUDAdrv.@profile only informs an external profiler to start.
│ The user is responsible for launching Julia under a CUDA profiler like `nvprof`.
│
│ For improved usability, launch Julia under the Nsight Systems profiler:
│ $ nsys launch -t cuda,cublas,cudnn,nvtx julia
└ @ CUDAdrv.Profile ~/.julia/packages/CUDAdrv/mCr0O/src/profile.jl:42
==21447== Profiling application: /opt/julia/1.2.0/bin/julia --project=. volumerhs.jl
==21447== Profiling result:
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*      Size  Throughput  SrcMemType  DstMemType           Device   Context    Stream  Name
81.2290s  12.307ms                    -               -         -         -         -  95.367MB  7.5676GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
90.5615s  1.8560us                    -               -         -         -         -        8B  4.1107MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
90.6591s  825.40us          (97657 1 1)       (256 1 1)        42        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_28 [35]
90.9422s  1.4720us                    -               -         -         -         -        8B  5.1830MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
90.9967s  114.62us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_29 [54]
91.4455s  1.4720us                    -               -         -         -         -        8B  5.1830MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
91.5221s  132.99us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_30 [70]
91.7757s  33.129ms                    -               -         -         -         -  267.03MB  7.8713GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
91.8091s  116.13us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_29 [79]
91.8093s  132.96us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_30 [81]
91.8094s  114.53us          (19532 1 1)       (256 1 1)        32        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_index_kernel_29 [86]
92.3601s  1.8240us                    -               -         -         -         -        8B  4.1828MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
92.4134s  140.83us          (19532 1 1)       (256 1 1)        38        0B        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_anonymous25_31 [102]
92.4136s  1.8560us                    -               -         -         -         -      100B  51.383MB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
92.4662s  12.088ms                    -               -         -         -         -  95.367MB  7.7047GB/s    Pageable      Device  Tesla V100-SXM2         1         7  [CUDA memcpy HtoD]
94.1333s  722.68us          (40000 1 1)         (5 5 1)       160  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__32 [119]
94.1412s  709.15us          (40000 1 1)         (5 5 1)       160  1.0977KB        0B         -           -           -           -  Tesla V100-SXM2         1         7  ptxcall_volumerhs__32 [122]

Regs: Number of registers used per CUDA thread. This number includes registers used internally by the CUDA driver and/or tools and can be more than what the compiler shows.
SSMem: Static shared memory allocated per CUDA block.
DSMem: Dynamic shared memory allocated per CUDA block.
SrcMemType: The type of source memory accessed by memory operation/copy
DstMemType: The type of destination memory accessed by memory operation/copy
```

**Comment by vchuravy** [comment]
Yeah `ldg` is a big performance boost, we should add that to `GPUifyLoops` so that we can use it appropriately.

**Comment by lcw** [comment]
Definitely!

What should we do on the CPU side?  Should we somehow have Cassette add the nontemporal flag to CPU loads?  Do we need to add mfence semantics?

**Pull request merged**
